// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pufxogvzyppvccxafxtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1ZnhvZ3Z6eXBwdmNjeGFmeHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNTEwNjUsImV4cCI6MjA2MTgyNzA2NX0.hg7Q7Okmso50NngAedr0v46xqOscgpEZ8jls6vCiONs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);